[package]
name = "tonic-clap"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_reflect.workspace = true
serde_json.workspace = true
serde.workspace = true
clap.workspace = true
tonic-clap-macros = { path = "../tonic-clap-macros" }

[dev-dependencies]
prost.workspace = true