[package]
name = "tonic-clap"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
proc-macro = true

[dependencies]
prost.workspace = true
proc-macro2.workspace = true
quote.workspace  = true
syn.workspace = true