// This file is @generated by prost-build.
/// The request message containing the user's name.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HelloRequest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HelloRequest2 {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub field1: ::core::option::Option<Field1>,
    #[prost(string, repeated, tag = "3")]
    pub field2: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Field1 {
    #[prost(string, tag = "1")]
    pub fname: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub fcount: i32,
}
/// The response message containing the greetings
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HelloReply {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HelloReply2 {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
pub struct MyStruct {}
pub struct MyStruct {}
