[package]
name = "tonic-clap-build"
version = "0.1.0"
edition = "2024"

[dependencies]
prost-build.workspace = true
proc-macro2.workspace = true
quote.workspace = true
tonic-build.workspace = true
heck.workspace = true